// Map configuration per electorate.
//
// Centers/zoom for every electorate that has a district boundary come from
// `boundary-index.json` (generated by scripts/generate-boundary-index.mjs from
// the GeoJSON in public/boundaries/). The boundary polygons themselves are NOT
// bundled here — they're served as static files and fetched client-side by
// slug (see population-map.tsx), keeping this module tiny.
//
// A few electorates (e.g. Imbonggu) have hand-tuned LLG centroids / colors /
// per-ward overrides; those are layered on top of the generated defaults.
import boundaryIndex from "./boundary-index.json";
import imbongguOverrides from "./imbonggu/overrides.json";

export type LatLng = [number, number];

export type ElectorateMapConfig = {
  electorateCenter: LatLng;
  defaultZoom: number;
  llgCenters: Record<string, LatLng>;
  llgSpread: Record<string, number>;
  llgColors: Record<string, string>;
  /** True when a GeoJSON boundary exists at /boundaries/<slug>.json. */
  hasBoundary?: boolean;
  overrides?: Record<string, LatLng>;
};

type BoundaryIndex = Record<string, { center: LatLng; zoom: number }>;
const INDEX = boundaryIndex as unknown as BoundaryIndex;

// Palette for LLG pins/legend when an electorate has no hand-picked colors.
export const LLG_PALETTE = [
  "#2563eb", "#16a34a", "#dc2626", "#9333ea", "#ea580c",
  "#0891b2", "#db2777", "#65a30d", "#7c3aed", "#ca8a04",
];

// Assigns a stable color to each LLG id, preferring any hand-picked base color.
export function buildLlgColors(
  llgIds: string[],
  base?: Record<string, string>
): Record<string, string> {
  const out: Record<string, string> = {};
  llgIds.forEach((id, i) => {
    out[id] = base?.[id] ?? LLG_PALETTE[i % LLG_PALETTE.length];
  });
  return out;
}

// Hand-tuned per-electorate configuration, layered over the generated defaults.
const HAND_CONFIGS: Record<
  string,
  Partial<Pick<ElectorateMapConfig, "llgCenters" | "llgSpread" | "llgColors" | "overrides">>
> = {
  imbonggu: {
    llgCenters: {
      "imbonggu-imbonggu": [-6.155, 143.92],
      "imbonggu-ialibu-basin": [-6.295, 144.0],
      "imbonggu-ialibu-urban": [-6.273, 143.988],
    },
    llgSpread: {
      "imbonggu-imbonggu": 0.07,
      "imbonggu-ialibu-basin": 0.06,
      "imbonggu-ialibu-urban": 0.012,
    },
    llgColors: {
      "imbonggu-imbonggu": "#2563eb",
      "imbonggu-ialibu-basin": "#16a34a",
      "imbonggu-ialibu-urban": "#dc2626",
    },
    overrides: imbongguOverrides as unknown as Record<string, LatLng>,
  },
};

function buildConfig(slug: string): ElectorateMapConfig {
  const idx = INDEX[slug];
  const hand = HAND_CONFIGS[slug] ?? {};
  return {
    electorateCenter: idx?.center ?? [-6.5, 145.0],
    defaultZoom: idx?.zoom ?? 7,
    llgCenters: hand.llgCenters ?? {},
    llgSpread: hand.llgSpread ?? {},
    llgColors: hand.llgColors ?? {},
    hasBoundary: !!idx,
    overrides: hand.overrides,
  };
}

// Every electorate with a boundary, plus any hand-config-only entries.
const ALL_SLUGS = Array.from(
  new Set([...Object.keys(INDEX), ...Object.keys(HAND_CONFIGS)])
);

export const ELECTORATE_MAP_CONFIGS: Record<string, ElectorateMapConfig> =
  Object.fromEntries(ALL_SLUGS.map((slug) => [slug, buildConfig(slug)]));

// Electorates that have a district boundary (used for UI ordering/labels).
export const ELECTORATES_WITH_MAPS = Object.keys(INDEX);
